name: Terraform Testing
one: [push]
jobs:
    Terraform-Fmt-Validate:
        runs-on: ubuntu-latest
        steps: 
          -run: echo "Testing our first workflow"

          - name: Checkout
            uses: action/checkout@v3

          - name: Setup Terraform 
            uses: hashicorp/setup-terraform@v1

          - name: Terraform Init
            env:
              AWS_ACCESS_KEY: s{{ secrets.AWS_ACCESS_KEY }}
              AWS_SECRET_ACCESS_KEY: s{{ secrets.AWS_SECRET_ACCESS_KEY }}
            run: terraform init

          - name: Terraform Format
            run: terraform fmt -check

          - name: Terraform Validate
            run: terraform validate 